<a href="https://colab.research.google.com/github/dilolol/IE423/blob/main/task8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
import os
os.getcwd()

'/content'

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [4]:
user_ratings_1 = pd.read_csv("/content/drive/MyDrive/UserRatings1.csv")
user_ratings_2 = pd.read_csv("/content/drive/MyDrive/UserRatings2.csv")
joke_text = pd.read_csv("/content/drive/MyDrive/JokeText.csv")


In [5]:
user_ratings_1.head()

JokeId  User1  User2  User3  User4  User5  User6  User7  User8  User9  ...  \
0       0   5.10  -8.79  -3.50   7.14  -8.79   9.22  -4.03   3.11  -3.64  ...   
1       1   4.90  -0.87  -2.91  -3.88  -0.58   9.37  -1.55   0.92  -3.35  ...   
2       2   1.75   1.99  -2.18  -3.06  -0.58  -3.93  -3.64   7.52  -6.46  ...   
3       3  -4.17  -4.61  -0.10   0.05   8.98   9.27  -6.99   0.49  -3.40  ...   
4       4   5.15   5.39   7.52   6.26   7.67   3.45   5.44  -0.58   1.26  ...   

   User36701  User36702  User36703  User36704  User36705  User36706  \
0        NaN        NaN        NaN        NaN        NaN        NaN   
1        NaN        NaN        NaN      -5.63        NaN      -6.07   
2        NaN        NaN        NaN        NaN        NaN       4.08   
3        NaN        NaN        NaN        NaN        NaN        NaN   
4       2.28      -0.49        5.1      -0.29      -3.54      -1.36   

   User36707  User36708  User36709  User36710  
0        NaN        NaN       2.91        NaN  
1        NaN      -1.60      -4.56        NaN  
2        NaN        NaN       8.98        NaN  
3        NaN        NaN        NaN        NaN  
4       7.48      -5.78       0.73       2.62  

[5 rows x 36711 columns]

In [6]:
user_ratings_2.head()

JokeId  User36711  User36712  User36713  User36714  User36715  User36716  \
0       0        NaN        NaN        NaN       3.93        NaN        NaN   
1       1        NaN        NaN        NaN        NaN        NaN        NaN   
2       2        NaN        NaN        NaN        NaN        NaN        NaN   
3       3        NaN        NaN        NaN        NaN        NaN        NaN   
4       4       5.68       1.07       8.11      -2.33      -5.83        8.2   

   User36717  User36718  User36719  ...  User73412  User73413  User73414  \
0        NaN        NaN        NaN  ...        NaN        NaN        NaN   
1        NaN        NaN       4.81  ...        NaN        NaN        NaN   
2        NaN        NaN        NaN  ...        NaN        NaN        NaN   
3        NaN        NaN        NaN  ...        NaN        NaN        NaN   
4      -5.83       1.94       0.10  ...       3.64       4.32       6.99   

   User73415  User73416  User73417  User73418  User73419  User73420  User73421  
0        NaN        NaN        NaN        NaN        NaN        NaN        NaN  
1        NaN        NaN        NaN        NaN        NaN        NaN        NaN  
2        NaN        NaN        NaN        NaN        NaN        NaN        NaN  
3        NaN        NaN        NaN        NaN        NaN        NaN        NaN  
4      -9.66       -8.4      -0.63       9.51      -7.67       -1.6        8.3  

[5 rows x 36712 columns]

In [7]:
joke_text.head()

JokeId                                           JokeText
0       0  A man visits the doctor. The doctor says "I ha...
1       1  This couple had an excellent relationship goin...
2       2  Q. What's 200 feet long and has 4 teeth? \n\nA...
3       3  Q. What's the difference between a man and a t...
4       4  Q.\tWhat's O. J. Simpson's Internet address? \...

In [8]:
joke_text.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   JokeId    100 non-null    int64 
 1   JokeText  100 non-null    object
dtypes: int64(1), object(1)
memory usage: 1.7+ KB


In [9]:
joke_text.describe()

JokeId
count  100.000000
mean    49.500000
std     29.011492
min      0.000000
25%     24.750000
50%     49.500000
75%     74.250000
max     99.000000

In [10]:
joke_text.isnull().sum()

JokeId      0
JokeText    0
dtype: int64

In [11]:
joke_text.shape

(100, 2)

In [12]:
joke_text.JokeId.unique()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [13]:
joke_text[joke_text['JokeId']==2]

JokeId                                           JokeText
2       2  Q. What's 200 feet long and has 4 teeth? \n\nA...

In [14]:
joke_text.JokeText[joke_text['JokeId']==2]

2    Q. What's 200 feet long and has 4 teeth? \n\nA...
Name: JokeText, dtype: object

In [15]:
user_ratings_1 = user_ratings_1.fillna(0)
user_ratings_1.head(3)

JokeId  User1  User2  User3  User4  User5  User6  User7  User8  User9  ...  \
0       0   5.10  -8.79  -3.50   7.14  -8.79   9.22  -4.03   3.11  -3.64  ...   
1       1   4.90  -0.87  -2.91  -3.88  -0.58   9.37  -1.55   0.92  -3.35  ...   
2       2   1.75   1.99  -2.18  -3.06  -0.58  -3.93  -3.64   7.52  -6.46  ...   

   User36701  User36702  User36703  User36704  User36705  User36706  \
0        0.0        0.0        0.0       0.00        0.0       0.00   
1        0.0        0.0        0.0      -5.63        0.0      -6.07   
2        0.0        0.0        0.0       0.00        0.0       4.08   

   User36707  User36708  User36709  User36710  
0        0.0        0.0       2.91        0.0  
1        0.0       -1.6      -4.56        0.0  
2        0.0        0.0       8.98        0.0  

[3 rows x 36711 columns]

In [16]:
user_ratings_1 = user_ratings_1.set_index('JokeId')

In [17]:
rating= user_ratings_1.T
rating.head(3)

JokeId    0     1     2     3     4     5     6     7     8     9   ...    90  \
User1   5.10  4.90  1.75 -4.17  5.15  1.75  4.76  3.30 -2.57 -1.41  ...  5.34   
User2  -8.79 -0.87  1.99 -4.61  5.39 -0.78  1.60  1.07 -8.69 -4.66  ...  3.59   
User3  -3.50 -2.91 -2.18 -0.10  7.52  1.26 -5.39  1.50 -8.40  4.37  ...  1.84   

JokeId    91    92    93    94    95    96    97    98    99  
User1  -4.61  3.59  7.18  0.92  6.31 -4.95 -0.19  3.25  4.37  
User2   1.21  2.86 -0.05 -1.75 -1.02 -0.97  4.13 -1.84  2.96  
User3  -4.03 -1.41  1.65 -3.79  3.98 -6.46 -6.89 -2.33 -7.38  

[3 rows x 100 columns]

In [18]:
def standardize(row):
    new_row=(row-row.mean())/(row.max()-row.min())
    return new_row
rating_new=rating.apply(standardize)
rating_new.tail(5)

JokeId           0         1         2         3         4         5   \
User36706 -0.039868 -0.323051  0.202347  0.060842 -0.083147 -0.199823   
User36707 -0.039868 -0.008869 -0.008833  0.060842  0.374410  0.412433   
User36708 -0.039868 -0.091685 -0.008833  0.060842 -0.311926  0.342402   
User36709  0.108905 -0.244894  0.455970  0.060842  0.025031 -0.537619   
User36710 -0.039868 -0.008869 -0.008833  0.060842  0.122857  0.102443   

JokeId           6         7         8         9   ...        90        91  \
User36706  0.174460 -0.267308  0.026121  0.384617  ... -0.053353 -0.032487   
User36707  0.211782 -0.091324  0.026121  0.399627  ... -0.053353 -0.032487   
User36708  0.285912  0.167475  0.026121  0.254182  ... -0.053353 -0.032487   
User36709 -0.461020  0.479069  0.026121  0.372194  ... -0.053353 -0.032487   
User36710  0.047671 -0.106335  0.026121  0.098385  ... -0.053353 -0.032487   

JokeId           92        93        94        95        96        97  \
User36706 -0.063158 -0.032998 -0.030613 -0.041373 -0.046037 -0.026194   
User36707 -0.063158 -0.032998 -0.030613 -0.041373 -0.046037 -0.026194   
User36708 -0.070922  0.297926 -0.030613 -0.041373 -0.046037 -0.026194   
User36709 -0.063158 -0.032998 -0.030613 -0.041373 -0.046037 -0.026194   
User36710 -0.063158 -0.032998 -0.030613 -0.041373 -0.046037 -0.026194   

JokeId           98        99  
User36706  0.187174 -0.030685  
User36707 -0.001232 -0.030685  
User36708 -0.001232 -0.030685  
User36709 -0.001232 -0.030685  
User36710 -0.001232 -0.030685  

[5 rows x 100 columns]

In [19]:
from sklearn.metrics.pairwise import cosine_similarity
similar_jokes=cosine_similarity(rating_new.T)
print(similar_jokes)

[[1.         0.38568338 0.37584773 ... 0.14149047 0.13785188 0.17719471]
 [0.38568338 1.         0.29923563 ... 0.21796435 0.12118666 0.23257434]
 [0.37584773 0.29923563 1.         ... 0.16210978 0.15459722 0.24316476]
 ...
 [0.14149047 0.21796435 0.16210978 ... 1.         0.30605987 0.41855551]
 [0.13785188 0.12118666 0.15459722 ... 0.30605987 1.         0.31737563]
 [0.17719471 0.23257434 0.24316476 ... 0.41855551 0.31737563 1.        ]]


In [20]:
ratings_df = pd.DataFrame(similar_jokes,index=rating_new.columns,columns=rating_new.columns)
ratings_df.head(5)

JokeId        0         1         2         3         4         5         6   \
JokeId                                                                         
0       1.000000  0.385683  0.375848  0.291442  0.171052  0.210574  0.187556   
1       0.385683  1.000000  0.299236  0.311917  0.210165  0.230772  0.187458   
2       0.375848  0.299236  1.000000  0.369021  0.204551  0.273645  0.176789   
3       0.291442  0.311917  0.369021  1.000000  0.188017  0.301707  0.167088   
4       0.171052  0.210165  0.204551  0.188017  1.000000  0.191531  0.209106   

JokeId        7         8         9   ...        90        91        92  \
JokeId                                ...                                 
0       0.179032  0.334988  0.324508  ...  0.154984  0.135963  0.172778   
1       0.122522  0.250778  0.268254  ...  0.129805  0.129684  0.146752   
2       0.173892  0.325820  0.298485  ...  0.139784  0.150650  0.168449   
3       0.091447  0.382876  0.244146  ...  0.147942  0.193558  0.173418   
4       0.169245  0.113175  0.163676  ...  0.101710  0.094779  0.110938   

JokeId        93        94        95        96        97        98        99  
JokeId                                                                        
0       0.184569  0.178359  0.171984  0.174901  0.141490  0.137852  0.177195  
1       0.119454  0.126617  0.134018  0.138494  0.217964  0.121187  0.232574  
2       0.147984  0.174403  0.148989  0.149066  0.162110  0.154597  0.243165  
3       0.168904  0.185710  0.187084  0.167126  0.260220  0.220651  0.301228  
4       0.084664  0.093018  0.075768  0.086929  0.161310  0.109796  0.198413  

[5 rows x 100 columns]

In [21]:
d=rating.describe()
d=d.T
d.describe()

count        mean         std           min         25%         50%  \
count    100.0  100.000000  100.000000  1.000000e+02  100.000000  100.000000   
mean   36710.0    0.642244    4.548575 -9.950000e+00   -1.948375    0.859600   
std        0.0    1.359968    0.629672  3.570612e-15    2.224343    1.567659   
min    36710.0   -2.977449    3.326084 -9.950000e+00   -7.430000   -3.640000   
25%    36710.0   -0.315005    3.806982 -9.950000e+00   -3.955000    0.000000   
50%    36710.0    0.611051    4.840098 -9.950000e+00   -1.240000    0.000000   
75%    36710.0    1.399410    5.011343 -9.950000e+00    0.000000    1.952500   
max    36710.0    3.623840    5.529352 -9.950000e+00    1.500000    4.420000   

              75%         max  
count  100.000000  100.000000  
mean     3.555950    9.498100  
std      2.037534    0.194877  
min      0.000000    9.370000  
25%      2.090000    9.370000  
50%      3.350000    9.370000  
75%      5.402500    9.572500  
max      6.840000   10.000000

In [22]:
def jokes_to_recommend(jokeid,rating):
    similar_score=ratings_df[jokeid]*(rating-0.64)
    similar_score=similar_score.sort_values(ascending=False)
    return similar_score
print(jokes_to_recommend(1,1))

JokeId
1     0.360000
24    0.149032
0     0.138846
51    0.125578
50    0.124851
        ...   
70    0.032016
78    0.030778
76    0.029281
74    0.025638
15    0.021048
Name: 1, Length: 100, dtype: float64


In [23]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

user_ratings = pd.merge(user_ratings_1, user_ratings_2, on='JokeId')
user_ratings.set_index('JokeId', inplace=True)

user_ratings_filled = user_ratings.apply(lambda row: row.fillna(row.mean()), axis=1)

joke_text['JokeText'] = joke_text['JokeText'].fillna('')

tfidf_vectorizer = TfidfVectorizer(analyzer='word', ngram_range=(1, 2), min_df=1, stop_words='english')
tfidf_matrix = tfidf_vectorizer.fit_transform(joke_text['JokeText'])

cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)


joke_ids = joke_text['JokeId']
indices = pd.Series(joke_text.index, index=joke_text['JokeId'])

In [24]:
def get_recommendations(joke_id, num_recommendations=5):
    idx = indices[joke_id]
    sim_scores = list(enumerate(cosine_sim[idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    sim_scores = sim_scores[1:num_recommendations+1]
    joke_indices = [i[0] for i in sim_scores]
    return joke_text.iloc[joke_indices]['JokeText']

recommended_jokes = get_recommendations(0)
print(recommended_jokes)

86    A man, recently completing a routine physical ...
67    A man piloting a hot air balloon discovers he ...
87    A Czechoslovakian man felt his eyesight was gr...
75    There once was a man and a woman that both  go...
31    A man arrives at the gates of heaven. St. Pete...
Name: JokeText, dtype: object


# Collaborative Filtering


In [16]:
def get_collaborative_recommendations(user_id, num_recommendations=5):
    # Access row by position using iloc since the index is not sequential
    user_ratings = user_ratings_filled.iloc[user_id]
    unrated_jokes = user_ratings[user_ratings.isnull()]

    # Handle the case where all jokes are rated
    if unrated_jokes.empty:
        return "User has rated all jokes"
    else:
      print(unrated_jokes)

    item_similarity = cosine_similarity(user_ratings_filled.T)

    joke_scores = np.dot(item_similarity, unrated_jokes.values)
    top_indices = np.argsort(joke_scores)[::-1][:num_recommendations]
    recommended_jokes = user_ratings_filled.columns[top_indices]
    return recommended_jokes

# Example usage
user_id = 1
recommended_jokes = get_collaborative_recommendations(user_id)
print(recommended_jokes)

User has rated all jokes
